# Clock
set_property PACKAGE_PIN W5 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk]

## Switches -> Inputs
# A[4:0]
set_property PACKAGE_PIN V17 [get_ports {a[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a[0]}]
set_property PACKAGE_PIN V16 [get_ports {a[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a[1]}]
set_property PACKAGE_PIN W16 [get_ports {a[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a[2]}]
set_property PACKAGE_PIN W17 [get_ports {a[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a[3]}]
set_property PACKAGE_PIN W15 [get_ports {a[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a[4]}]

# B[4:0]
set_property PACKAGE_PIN V15 [get_ports {b[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {b[0]}]
set_property PACKAGE_PIN W14 [get_ports {b[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {b[1]}]
set_property PACKAGE_PIN W13 [get_ports {b[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {b[2]}]
set_property PACKAGE_PIN V2 [get_ports {b[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {b[3]}]
set_property PACKAGE_PIN T3 [get_ports {b[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {b[4]}]

# ALUControl[1:0]
set_property PACKAGE_PIN T2 [get_ports {ALUControl[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ALUControl[0]}]
set_property PACKAGE_PIN R3 [get_ports {ALUControl[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ALUControl[1]}]

## LEDs -> Outputs
# Result[4:0]
set_property PACKAGE_PIN U16 [get_ports {Result[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Result[0]}]
set_property PACKAGE_PIN E19 [get_ports {Result[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Result[1]}]
set_property PACKAGE_PIN U19 [get_ports {Result[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Result[2]}]
set_property PACKAGE_PIN V19 [get_ports {Result[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Result[3]}]
set_property PACKAGE_PIN W18 [get_ports {Result[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Result[4]}]

# ALUFlags[3:0]
set_property PACKAGE_PIN U15 [get_ports {ALUFlags[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ALUFlags[0]}]
set_property PACKAGE_PIN U14 [get_ports {ALUFlags[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ALUFlags[1]}]
set_property PACKAGE_PIN V14 [get_ports {ALUFlags[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ALUFlags[2]}]
set_property PACKAGE_PIN V13 [get_ports {ALUFlags[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ALUFlags[3]}]
